### ISSUE TITLE
Error Injecting

### ISSUE THREAD

**Issue by Bobbyjeff9876** [LeviTheOtaku/Levisploit#1]
A message box is showing saying "Injection Failed. Maybe you are missing somthing or other stuff."

The Axon console window opened but didnt write anything either.

Do I need to update the adresses?

**Comment by LeviTheOtaku** [comment]
Yup!

**Comment by EpicGamerUsername** [comment]
Hey, I'm sorry for being a total noob here but how do I update the addresses?
